import type { RunState } from '@/types/run';

export const RUN_INITIAL_STATE: RunState = {
  isActive: false,
  mode: 'normal',
  runId: '',
  seed: null,
  startedAt: null,
  authorityAttempt: null,
  pendingAuthorityStart: null,
  isEnding: false,
  saveStatus: 'idle',
  saveError: null,
  saveFailureKind: null,
  completedRunSnapshot: null,
  serverProgression: null,
  rewardsApplied: false,
  completedCombatStats: [],
  nextItemInstanceId: 1,
  team: [],
  runLevel: 1,
  biomesVisited: [],
  currentBiome: null,
  inventory: [],
  runeIds: [],
  augmentIds: [],
  pendingAugmentIds: [],
  lastCombatRewards: null,
  pendingSpellUpgradeChampionIds: [],
  gold: 0,
  currentWave: 1,
  totalWavesCompleted: 0,
  biomeMaps: [],
  currentBiomeIndex: 0,
  currentNodeId: null,
  completedNodeIds: [],
  claimedEncounterNodeIds: [],
  pendingEncounter: null,
  currentEncounter: null,
};
