BEGIN;

CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name VARCHAR(32) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT profiles_display_name_not_blank
    CHECK (LENGTH(TRIM(display_name)) BETWEEN 1 AND 32)
);

CREATE TABLE public.runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  mode VARCHAR(16) NOT NULL DEFAULT 'normal',
  daily_key DATE,
  seed BIGINT NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'active',
  won BOOLEAN NOT NULL DEFAULT FALSE,
  run_level INTEGER NOT NULL DEFAULT 1,
  waves_completed INTEGER NOT NULL DEFAULT 0,
  gold_earned INTEGER NOT NULL DEFAULT 0,
  score INTEGER NOT NULL DEFAULT 0,
  biomes_visited JSONB NOT NULL DEFAULT '[]'::JSONB,
  started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at TIMESTAMPTZ,
  CONSTRAINT runs_mode_valid CHECK (mode IN ('normal', 'daily')),
  CONSTRAINT runs_status_valid CHECK (status IN ('active', 'completed', 'abandoned')),
  CONSTRAINT runs_level_positive CHECK (run_level >= 1),
  CONSTRAINT runs_totals_non_negative
    CHECK (waves_completed >= 0 AND gold_earned >= 0 AND score >= 0),
  CONSTRAINT runs_daily_fields_consistent CHECK (
    (mode = 'daily' AND daily_key IS NOT NULL)
    OR (mode = 'normal' AND daily_key IS NULL)
  ),
  CONSTRAINT runs_completion_consistent CHECK (
    (status = 'active' AND completed_at IS NULL)
    OR (status <> 'active' AND completed_at IS NOT NULL)
  )
);

CREATE TABLE public.run_champions (
  run_id BIGINT NOT NULL REFERENCES public.runs(id) ON DELETE CASCADE,
  champion_id VARCHAR(64) NOT NULL,
  team_position SMALLINT NOT NULL,
  champion_level INTEGER NOT NULL DEFAULT 1,
  current_hp INTEGER,
  current_xp INTEGER NOT NULL DEFAULT 0,
  kills INTEGER NOT NULL DEFAULT 0,
  total_damage INTEGER NOT NULL DEFAULT 0,
  survived BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (run_id, champion_id),
  CONSTRAINT run_champions_position_unique UNIQUE (run_id, team_position),
  CONSTRAINT run_champions_position_valid CHECK (team_position BETWEEN 1 AND 5),
  CONSTRAINT run_champions_values_valid CHECK (
    champion_level >= 1
    AND (current_hp IS NULL OR current_hp >= 0)
    AND current_xp >= 0
    AND kills >= 0
    AND total_damage >= 0
  )
);

CREATE TABLE public.run_inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id BIGINT NOT NULL REFERENCES public.runs(id) ON DELETE CASCADE,
  instance_id VARCHAR(96) NOT NULL,
  item_id VARCHAR(64) NOT NULL,
  equipped_to_champion_id VARCHAR(64),
  acquired_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT run_inventory_instance_unique UNIQUE (run_id, instance_id),
  CONSTRAINT run_inventory_equipped_champion_fk
    FOREIGN KEY (run_id, equipped_to_champion_id)
    REFERENCES public.run_champions(run_id, champion_id)
    ON DELETE SET NULL (equipped_to_champion_id)
);

CREATE TABLE public.champion_mastery (
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  champion_id VARCHAR(64) NOT NULL,
  candies INTEGER NOT NULL DEFAULT 0,
  mastery_level SMALLINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, champion_id),
  CONSTRAINT champion_mastery_values_valid
    CHECK (candies >= 0 AND mastery_level BETWEEN 0 AND 4)
);

CREATE TABLE public.daily_leaderboard (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  daily_key DATE NOT NULL,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  run_id BIGINT NOT NULL UNIQUE REFERENCES public.runs(id) ON DELETE CASCADE,
  score INTEGER NOT NULL,
  waves_completed INTEGER NOT NULL,
  run_level INTEGER NOT NULL,
  completed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT daily_leaderboard_user_once UNIQUE (daily_key, user_id),
  CONSTRAINT daily_leaderboard_values_valid
    CHECK (score >= 0 AND waves_completed >= 0 AND run_level >= 1)
);

CREATE INDEX runs_user_started_idx ON public.runs (user_id, started_at DESC);
CREATE INDEX runs_daily_key_score_idx ON public.runs (daily_key, score DESC);
CREATE INDEX daily_leaderboard_ranking_idx
  ON public.daily_leaderboard (daily_key, score DESC, completed_at ASC);

-- SUPABASE SECURITY START

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.run_champions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.run_inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.champion_mastery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_leaderboard ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles are publicly readable"
  ON public.profiles FOR SELECT
  TO anon, authenticated
  USING (TRUE);

CREATE POLICY "Users can update their profile"
  ON public.profiles FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = id)
  WITH CHECK ((SELECT auth.uid()) = id);

CREATE POLICY "Users can read their runs"
  ON public.runs FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can create their runs"
  ON public.runs FOR INSERT
  TO authenticated
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can update their runs"
  ON public.runs FOR UPDATE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can delete their runs"
  ON public.runs FOR DELETE
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can manage their run champions"
  ON public.run_champions FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.runs
      WHERE runs.id = run_champions.run_id
        AND runs.user_id = (SELECT auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.runs
      WHERE runs.id = run_champions.run_id
        AND runs.user_id = (SELECT auth.uid())
    )
  );

CREATE POLICY "Users can manage their run inventory"
  ON public.run_inventory FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.runs
      WHERE runs.id = run_inventory.run_id
        AND runs.user_id = (SELECT auth.uid())
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.runs
      WHERE runs.id = run_inventory.run_id
        AND runs.user_id = (SELECT auth.uid())
    )
  );

CREATE POLICY "Users can read their mastery"
  ON public.champion_mastery FOR SELECT
  TO authenticated
  USING ((SELECT auth.uid()) = user_id);

CREATE POLICY "Users can manage their mastery"
  ON public.champion_mastery FOR ALL
  TO authenticated
  USING ((SELECT auth.uid()) = user_id)
  WITH CHECK ((SELECT auth.uid()) = user_id);

CREATE POLICY "Leaderboard is publicly readable"
  ON public.daily_leaderboard FOR SELECT
  TO anon, authenticated
  USING (TRUE);

CREATE POLICY "Users can add their leaderboard result"
  ON public.daily_leaderboard FOR INSERT
  TO authenticated
  WITH CHECK (
    (SELECT auth.uid()) = user_id
    AND EXISTS (
      SELECT 1 FROM public.runs
      WHERE runs.id = daily_leaderboard.run_id
        AND runs.user_id = (SELECT auth.uid())
        AND runs.mode = 'daily'
        AND runs.status = 'completed'
    )
  );

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.profiles (id, display_name)
  VALUES (
    NEW.id,
    COALESCE(NULLIF(TRIM(NEW.raw_user_meta_data ->> 'display_name'), ''), 'Player')
  );
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- SUPABASE SECURITY END

COMMIT;
