// Generated from config/authority-versions.json by npm run authority:generate.
// Do not edit this file directly.

export const AUTHORITY_FEATURE_BITS = {"canonicalProgression":1,"manualCombat":2,"canonicalEncounters":4} as const;
export const AUTHORITY_ENGINE_FEATURE_MASKS: readonly number[] = [-1,0,0,2,3,3,7,7,7,7,7,7,7,7,7,7,7];
export const CURRENT_AUTHORITY_VERSION = {
  "engine": "run-engine-v16",
  "gameplay": 16,
  "contentHash": "52b685ec394cad4d71c98544ac15df51a1173c0e89c0200f5c4ea07c4355d016",
  "dailyScore": 14
} as const;
