// Generated from config/authority-versions.json by npm run authority:generate.
// Do not edit this file directly.

export const AUTHORITY_FEATURE_BITS = {"canonicalProgression":1,"manualCombat":2,"canonicalEncounters":4} as const;
export const AUTHORITY_ENGINE_FEATURE_MASKS: readonly number[] = [-1,0,0,2,3,3,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7];
export const CURRENT_AUTHORITY_VERSION = {
  "engine": "run-engine-v20",
  "gameplay": 20,
  "contentHash": "8308ebe66c3ee45850b68560b0449b6660b24c2a0e81a5070f6d1794620cac91",
  "dailyScore": 15
} as const;
