// Generated from config/authority-versions.json by npm run authority:generate.
// Do not edit this file directly.

export const AUTHORITY_FEATURE_BITS = {"canonicalProgression":1,"manualCombat":2,"canonicalEncounters":4} as const;
export const AUTHORITY_ENGINE_FEATURE_MASKS: readonly number[] = [-1,0,0,2,3,3,7,7,7,7,7,7,7,7,7,7,7,7,7,7];
export const CURRENT_AUTHORITY_VERSION = {
  "engine": "run-engine-v19",
  "gameplay": 19,
  "contentHash": "45a1dbb93be5a25281ba6fce56517be382ddff6210dce9a55ef3d1ac7c971099",
  "dailyScore": 15
} as const;
